using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

using Xunit;
using Amazon.Lambda.Core;
using Amazon.Lambda.TestUtilities;
using Amazon.Lambda.APIGatewayEvents;

using Newtonsoft.Json;

using ValheimServerGUI.Serverless;


namespace ValheimServerGUI.Serverless.Tests
{
    public class ValuesControllerTests
    {
        [Fact]
        public Task TestGet()
        {
            return Task.CompletedTask;
            // todo: (jb, 5/16/21) This was the test generated by the AWS scaffolder.
            // Need to come back and write tests for the real Serverless application.

            //var lambdaFunction = new LambdaEntryPoint();

            //var requestStr = File.ReadAllText("./SampleRequests/ValuesController-Get.json");
            //var request = JsonConvert.DeserializeObject<APIGatewayProxyRequest>(requestStr);
            //var context = new TestLambdaContext();
            //var response = await lambdaFunction.FunctionHandlerAsync(request, context);

            //Assert.Equal(200, response.StatusCode);
            //Assert.Equal("[\"value1\",\"value2\"]", response.Body);
            //Assert.True(response.MultiValueHeaders.ContainsKey("Content-Type"));
            //Assert.Equal("application/json; charset=utf-8", response.MultiValueHeaders["Content-Type"][0]);
        }
    }
}
