//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ValheimServerGUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ValheimServerGUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddImmediateWindow_16x {
            get {
                object obj = ResourceManager.GetObject("AddImmediateWindow_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ApplicationIcon {
            get {
                object obj = ResourceManager.GetObject("ApplicationIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Unofficial) Valheim Dedicated Server GUI.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Cancel_16x {
            get {
                object obj = ResourceManager.GetObject("Cancel_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Copy_16x {
            get {
                object obj = ResourceManager.GetObject("Copy_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string DefaultBackupCount {
            get {
                return ResourceManager.GetString("DefaultBackupCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43200.
        /// </summary>
        internal static string DefaultBackupIntervalLong {
            get {
                return ResourceManager.GetString("DefaultBackupIntervalLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7200.
        /// </summary>
        internal static string DefaultBackupIntervalShort {
            get {
                return ResourceManager.GetString("DefaultBackupIntervalShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %ProgramFiles(x86)%\Steam\steamapps\common\Valheim\valheim.exe.
        /// </summary>
        internal static string DefaultGamePath {
            get {
                return ResourceManager.GetString("DefaultGamePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1800.
        /// </summary>
        internal static string DefaultSaveInterval {
            get {
                return ResourceManager.GetString("DefaultSaveInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %ProgramFiles(x86)%\Steam\steamapps\common\Valheim dedicated server\valheim_server.exe.
        /// </summary>
        internal static string DefaultServerPath {
            get {
                return ResourceManager.GetString("DefaultServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2456.
        /// </summary>
        internal static string DefaultServerPort {
            get {
                return ResourceManager.GetString("DefaultServerPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string DefaultServerProfileName {
            get {
                return ResourceManager.GetString("DefaultServerProfileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %USERPROFILE%\AppData\LocalLow\IronGate\Valheim.
        /// </summary>
        internal static string DefaultValheimSaveFolder {
            get {
                return ResourceManager.GetString("DefaultValheimSaveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DiscordLogo {
            get {
                object obj = ResourceManager.GetObject("DiscordLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DonateLogo {
            get {
                object obj = ResourceManager.GetObject("DonateLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FolderInformation_16x {
            get {
                object obj = ResourceManager.GetObject("FolderInformation_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GitHubLogo {
            get {
                object obj = ResourceManager.GetObject("GitHubLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loading_16x {
            get {
                object obj = ResourceManager.GetObject("Loading_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Loading_Blue_16x {
            get {
                object obj = ResourceManager.GetObject("Loading_Blue_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %USERPROFILE%\AppData\LocalLow\Runeberry\ValheimServerGUI\logs.
        /// </summary>
        internal static string LogsFolderPath {
            get {
                return ResourceManager.GetString("LogsFolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewBug_16x {
            get {
                object obj = ResourceManager.GetObject("NewBug_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NewFile_16x {
            get {
                object obj = ResourceManager.GetObject("NewFile_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenFile_16x {
            get {
                object obj = ResourceManager.GetObject("OpenFile_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenFolder_16x {
            get {
                object obj = ResourceManager.GetObject("OpenFolder_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenWeb_16x {
            get {
                object obj = ResourceManager.GetObject("OpenWeb_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %USERPROFILE%\AppData\LocalLow\Runeberry\ValheimServerGUI\players.json.
        /// </summary>
        internal static string PlayerListFilePath {
            get {
                return ResourceManager.GetString("PlayerListFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Restart_16x {
            get {
                object obj = ResourceManager.GetObject("Restart_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Run_16x {
            get {
                object obj = ResourceManager.GetObject("Run_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap RuneberryLogo {
            get {
                object obj = ResourceManager.GetObject("RuneberryLogo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save_16x {
            get {
                object obj = ResourceManager.GetObject("Save_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings_16x {
            get {
                object obj = ResourceManager.GetObject("Settings_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusCriticalError_16x {
            get {
                object obj = ResourceManager.GetObject("StatusCriticalError_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusInformation_16x {
            get {
                object obj = ResourceManager.GetObject("StatusInformation_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusNotStarted_16x {
            get {
                object obj = ResourceManager.GetObject("StatusNotStarted_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusOK_16x {
            get {
                object obj = ResourceManager.GetObject("StatusOK_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusPause_grey_16x {
            get {
                object obj = ResourceManager.GetObject("StatusPause_grey_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusRun_16x {
            get {
                object obj = ResourceManager.GetObject("StatusRun_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusStop_16x {
            get {
                object obj = ResourceManager.GetObject("StatusStop_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap StatusWarning_16x {
            get {
                object obj = ResourceManager.GetObject("StatusWarning_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stop_16x {
            get {
                object obj = ResourceManager.GetObject("Stop_16x", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap UnsyncedCommits_16x_Horiz {
            get {
                object obj = ResourceManager.GetObject("UnsyncedCommits_16x_Horiz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.00:00:00.
        /// </summary>
        internal static string UpdateCheckInterval {
            get {
                return ResourceManager.GetString("UpdateCheckInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://discord.gg/HBsNJTY.
        /// </summary>
        internal static string UrlDiscord {
            get {
                return ResourceManager.GetString("UrlDiscord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.buymeacoffee.com/runeberry.
        /// </summary>
        internal static string UrlDonate {
            get {
                return ResourceManager.GetString("UrlDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dotnet.microsoft.com/download/dotnet/6.0.
        /// </summary>
        internal static string UrlDotnetDownload {
            get {
                return ResourceManager.GetString("UrlDotnetDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.ipify.org?format=json.
        /// </summary>
        internal static string UrlExternalIpLookup {
            get {
                return ResourceManager.GetString("UrlExternalIpLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://api.github.com/repos/runeberry/ValheimServerGUI.
        /// </summary>
        internal static string UrlGithubApi {
            get {
                return ResourceManager.GetString("UrlGithubApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/runeberry/ValheimServerGUI.
        /// </summary>
        internal static string UrlGithubApplication {
            get {
                return ResourceManager.GetString("UrlGithubApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/runeberry.
        /// </summary>
        internal static string UrlGithubOrganization {
            get {
                return ResourceManager.GetString("UrlGithubOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/runeberry/ValheimServerGUI/wiki.
        /// </summary>
        internal static string UrlHelp {
            get {
                return ResourceManager.GetString("UrlHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/runeberry/ValheimServerGUI/wiki/Connecting-to-your-Server.
        /// </summary>
        internal static string UrlPortForwardingGuide {
            get {
                return ResourceManager.GetString("UrlPortForwardingGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://u312zw22d6.execute-api.us-east-1.amazonaws.com/Prod.
        /// </summary>
        internal static string UrlRuneberryApi {
            get {
                return ResourceManager.GetString("UrlRuneberryApi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/runeberry/ValheimServerGUI/releases.
        /// </summary>
        internal static string UrlUpdates {
            get {
                return ResourceManager.GetString("UrlUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %USERPROFILE%\AppData\LocalLow\Runeberry\ValheimServerGUI\userprefs.txt.
        /// </summary>
        internal static string UserPrefsFilePath {
            get {
                return ResourceManager.GetString("UserPrefsFilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %USERPROFILE%\AppData\LocalLow\Runeberry\ValheimServerGUI\userprefs.json.
        /// </summary>
        internal static string UserPrefsFilePathV2 {
            get {
                return ResourceManager.GetString("UserPrefsFilePathV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.valheimgame.com/.
        /// </summary>
        internal static string ValheimGameSiteUrl {
            get {
                return ResourceManager.GetString("ValheimGameSiteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 892970.
        /// </summary>
        internal static string ValheimSteamAppId {
            get {
                return ResourceManager.GetString("ValheimSteamAppId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vsg_logo_16 {
            get {
                object obj = ResourceManager.GetObject("vsg_logo_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
